#!/bin/bash
echo "计算机科学领域英文论文查重"
echo "https://www.acemap.info/similarity-check"
echo "计算机论文投稿背景知识"
echo "【1】CCF(China Computer Federation)"
echo "中国计算机学会（CCF）受中国科学技术协会（China Association for Science and Technology）领导，"
echo "会刊有：《计算机学报》、《计算机科学技术学报》、《软件学报》等"
echo "CCF对于各种计算机刊物、会议进行统一评级，一般分为以下三个等级："
echo "CCF A"
echo "CCF B"
echo "CCF C"
echo "人工智能：刊物、会议评级分类https://www.ccf.org.cn/Academic_Evaluation/AI/"
echo "计算机网络：刊物、会议评级分类https://www.ccf.org.cn/Academic_Evaluation/CN/"
echo "计算机体系结构/并行与分布计算/存储系统：刊物、会议评级分类https://www.ccf.org.cn/Academic_Evaluation/ARCH_DCP_SS/"
echo "【2】SCI(Scientific Citation Index)"
echo "科学引文索引（SCI）是美国科学信息研究所编辑出版的科研期刊，该刊物以论文的影响因子为评价指标。"
echo "【3】EI(The Engineering Index)"
echo "工程索引（EI）是由美国工程师学会联合会创办的历史上最悠久的一部大型综合性检索工具，论文更偏向工程。"
echo "【4】Nature"
echo "《自然》是科学界普遍关注的、国际性、跨学科的周刊类科学杂志。"
echo "【5】Science"
echo "《科学》杂志属于综合性科学杂志。它的科学新闻报道、综述、分析、书评等部分，都是权威的科普资料，该杂志也适合一般读者阅读。"
echo "【6】AAAI(American Association for Artificial Intelligence)"
echo "美国人工智能协会"
echo "【7】IEEE(Institute of Electrical and Electronics Engineers)"
echo "电气和电子工程师协会"
echo "【8】ACM(Association for Computing Machinery)"
echo "国际计算机学会"
echo "【9】AAAI(AAAI Conference on Artificial Intelligence)"
echo "人工智能A类会议"
echo "【10】INFOCOM(IEEE International Conference on Computer Communications)"
echo "计算机网络A类会议"
echo "【11】GLOBECOM(IEEE Global Communications Conference)"
echo "计算机网络C类会议"
echo "【12】IPDPS(International Parallel & Distributed Processing Symposium)"
echo "计算机体系结构/并行与分布计算/存储系统B类会议"
echo "【13】ICDCS(International Conference on Distributed Computing Systems) https://icdcs2021.us/"
echo "计算机体系结构/并行与分布计算/存储系统B类会议"
echo "【14】ICPP(International Conference on Parallel Processing)"
echo "计算机体系结构/并行与分布计算/存储系统B类会议"
echo "【15】TPDS(IEEE Transactions on Parallel and Distributed Systems)"
echo "计算机体系结构/并行与分布计算/存储系统A类刊物"
echo "【16】TMC(IEEE Transactions on Mobile Computing)"
echo "计算机网络A类刊物"
echo "【17】TON(IEEE/ACM Transactions on Networking)"
echo "计算机网络A类刊物"
echo "【18】JSAC(IEEE/ACM Transactions on Networking)"
echo "计算机网络A类刊物"
echo "【19】WASA(International Conference on Wireless Algorithms, Systems, and Applications)"
echo "计算机网络C类会议"
echo "【20】ICNP(International Conference on Network Protocols)"
echo "计算机网络B类会议"
echo "【21】ICC(IEEE International Conference on Communications)"
echo "计算机网络C类会议"
echo "【22】IWQoS(International Workshop on Quality of Service) https://iwqos2021.ieee-iwqos.org/"
echo "计算机网络B类会议"